#!/bin/bash

VOLUME=$(amixer -c1 sget Master | egrep -o -m 1 "[0-9]+%")

STATE=$(amixer -c1 sget Master | egrep -m 1 'Playback.*?\[o' | egrep -o '\[o.+\]')

# # What to display in i3bar:
if [[ $STATE == '[off]' ]]; then
	echo OFF
else
        VOLUME=$(echo -e "$VOLUME" | egrep -o "[0-9]+")
        if [ "$VOLUME" -lt "33" ]; then
					echo -e "$VOLUME \uf026"

        elif [ "$VOLUME" -lt "66" ]; then
					echo -e " $VOLUME \uf027"
        else
					echo -e "$VOLUME \uf028"
        fi
fi

# Use mouse to change volume and toggle mute in i3bar:
case $BLOCK_BUTTON in
  1) ~/.i3/scripts/vol-notify ;;
  # Right click to toggle mute
  3) amixer -q sset Master toggle & ~/.i3/scripts/vol-notify ;;
  # Scroll up to increase volume
  4) amixer -q sset Master 5%+ & echo "$ICON$VOLUME";;
  # Scroll down to decrease volume
  5) amixer -q sset Master 5%- & echo "$ICON$VOLUME";;
esac
