#! /bin/bash

# Author: Sebastiaan Van Hoecke

set -o errexit
set -o pipefail
set -o nounset

#variables
readonly ARGS=1
readonly VERSION=0.0.1
readonly SCRIPT_NAME=$(basename "${0}")
readonly SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
IFS=$'\t\n'   # Split on newlines and tabs (but not on spaces)

main(){
  echo $SCRIPT_NAME
  echo $SCRIPT_DIR
  check_args "${@}"

}

#functions
check_args(){
  if [ $# -eq $ARGS  ]  
	  then
		  if [ "$1" = "-h"  ] || [ "$1" = "--help"  ]
			  then 
       	usage
			  exit 2
		  fi
  else
	  echo "Expected ${ARGS} argument(s), got ${#}" >&2
	  usage
	  exit 2
  fi
}

usage(){
  cat << _EOF_
  Usage: ${0} []OPTIONS]... [ARGS]...

    description


  OPTIONS:

  EXAMPLES:

_EOF_
}

main "${@}"

# cursor: 20 del   
