#! /usr/bin/python

import sys


class Main(object):

    def __init__(self):

        if len(sys.argv) == 2:
            print("%s" % (sys.argv[1]))
        else:
            sys.stderr.write("Usage: %s <name>\n" % (sys.argv[0]))


if __name__ == "__main__":

    main = Main()


# cursor: 3 del 
